import type {
  StickerCategoryMeta,
  StickerDefinition,
} from "@/types/stickers";
import type { AvatarConfig } from "@/types";

export const STICKER_CATEGORIES: StickerCategoryMeta[] = [
  { id: "all", label: "All" },
  { id: "favorites", label: "Favorites" },
  { id: "greetings", label: "Greetings" },
  { id: "masonic-life", label: "Masonic Life" },
  { id: "degrees", label: "Degrees" },
  { id: "tools", label: "Tools" },
  { id: "humor", label: "Humor" },
  { id: "celebration", label: "Celebration" },
  { id: "expressions", label: "Expressions" },
  { id: "daily", label: "Daily Life" },
];

/** First-pack sticker library — data-driven so packs can grow later. */
export const STICKER_CATALOG: StickerDefinition[] = [
  {
    id: "good-morning-brother",
    name: "Good Morning, Brother",
    category: "greetings",
    text: "GOOD MORNING,\nBROTHER",
    pose: "wave",
    expression: "friendly",
    props: ["sun", "coffee"],
    background: "coffee",
    featured: true,
  },
  {
    id: "good-evening-brother",
    name: "Good Evening, Brother",
    category: "greetings",
    text: "GOOD EVENING,\nBROTHER",
    pose: "idle",
    expression: "smile",
    props: ["moon"],
    background: "lodge-night",
  },
  {
    id: "have-a-blessed-day",
    name: "Have a Blessed Day",
    category: "greetings",
    text: "HAVE A\nBLESSED DAY",
    pose: "idle",
    expression: "friendly",
    props: ["spark"],
    background: "parchment",
  },
  {
    id: "greetings-brother",
    name: "Greetings, Brother",
    category: "greetings",
    text: "GREETINGS,\nBROTHER",
    pose: "wave",
    expression: "smile",
    background: "gold-ring",
  },
  {
    id: "on-the-square",
    name: "On the Square",
    category: "masonic-life",
    text: "ON THE\nSQUARE",
    pose: "power",
    expression: "confident",
    apron: "mm",
    tool: "gavel",
    background: "gold-ring",
    featured: true,
  },
  {
    id: "well-met",
    name: "Well Met",
    category: "masonic-life",
    text: "WELL MET",
    pose: "wave",
    expression: "friendly",
    apron: "plain",
    background: "parchment",
    featured: true,
  },
  {
    id: "traveling-brother",
    name: "Traveling Brother",
    category: "masonic-life",
    text: "TRAVELING\nBROTHER",
    pose: "lean",
    expression: "confident",
    props: ["columns-pair"],
    background: "columns",
    featured: true,
  },
  {
    id: "lodge-night",
    name: "Lodge Night",
    category: "masonic-life",
    text: "LODGE\nNIGHT",
    pose: "power",
    expression: "smile",
    apron: "mm",
    props: ["moon", "columns-pair"],
    background: "lodge-night",
    featured: true,
  },
  {
    id: "see-you-at-lodge",
    name: "See You at Lodge",
    category: "masonic-life",
    text: "SEE YOU\nAT LODGE",
    pose: "wave",
    expression: "friendly",
    background: "columns",
    featured: true,
  },
  {
    id: "time-for-lodge",
    name: "Time for Lodge",
    category: "masonic-life",
    text: "TIME FOR\nLODGE",
    pose: "idle",
    expression: "confident",
    tool: "gavel",
    background: "parchment",
  },
  {
    id: "raising-day",
    name: "Raising Day",
    category: "degrees",
    text: "RAISING\nDAY",
    pose: "power",
    expression: "confident",
    apron: "mm",
    props: ["spark"],
    background: "gold-ring",
    featured: true,
  },
  {
    id: "master-mason",
    name: "Master Mason",
    category: "degrees",
    text: "MASTER\nMASON",
    pose: "idle",
    expression: "confident",
    apron: "mm",
    tool: "gavel",
    background: "gold-ring",
    featured: true,
  },
  {
    id: "entered-apprentice",
    name: "Entered Apprentice",
    category: "degrees",
    text: "ENTERED\nAPPRENTICE",
    pose: "idle",
    expression: "friendly",
    apron: "ea",
    background: "parchment",
  },
  {
    id: "fellow-craft",
    name: "Fellow Craft",
    category: "degrees",
    text: "FELLOW\nCRAFT",
    pose: "lean",
    expression: "smile",
    apron: "fc",
    background: "parchment",
  },
  {
    id: "journey-continues",
    name: "The Journey Continues",
    category: "degrees",
    text: "THE JOURNEY\nCONTINUES",
    pose: "lean",
    expression: "confident",
    props: ["ashlar"],
    background: "journey",
    featured: true,
  },
  {
    id: "working-tools",
    name: "Working Tools",
    category: "tools",
    text: "WORKING\nTOOLS",
    pose: "idle",
    expression: "smile",
    tool: "trowel",
    props: ["ashlar"],
    background: "parchment",
  },
  {
    id: "gavel-ready",
    name: "Gavel Ready",
    category: "tools",
    text: "GAVEL\nREADY",
    pose: "power",
    expression: "confident",
    tool: "gavel",
    props: ["gavel-float"],
    background: "gold-ring",
  },
  {
    id: "on-the-level",
    name: "On the Level",
    category: "tools",
    text: "ON THE\nLEVEL",
    pose: "idle",
    expression: "smile",
    tool: "level",
    background: "parchment",
  },
  {
    id: "who-moved-gavel",
    name: "Who Moved My Gavel?",
    category: "humor",
    text: "WHO MOVED\nMY GAVEL?",
    pose: "lean",
    expression: "wink",
    tool: "gavel",
    background: "parchment",
  },
  {
    id: "coffee-promised",
    name: "I Was Told There Would Be Coffee",
    category: "humor",
    text: "I WAS TOLD THERE\nWOULD BE COFFEE",
    pose: "idle",
    expression: "laugh",
    mouth: "grin",
    props: ["coffee"],
    background: "coffee",
  },
  {
    id: "lodge-tonight",
    name: "Lodge Tonight?",
    category: "humor",
    text: "LODGE\nTONIGHT?",
    pose: "wave",
    expression: "wink",
    background: "lodge-night",
  },
  {
    id: "above-my-degree",
    name: "That's Above My Degree",
    category: "humor",
    text: "THAT'S ABOVE\nMY DEGREE",
    pose: "lean",
    expression: "laugh",
    mouth: "grin",
    background: "parchment",
  },
  {
    id: "square-business",
    name: "Square Business",
    category: "humor",
    text: "SQUARE\nBUSINESS",
    pose: "power",
    expression: "confident",
    apron: "mm",
    background: "gold-ring",
  },
  {
    id: "congrats-brother",
    name: "Congratulations, Brother",
    category: "celebration",
    text: "CONGRATULATIONS,\nBROTHER",
    pose: "power",
    expression: "laugh",
    mouth: "grin",
    props: ["spark"],
    background: "gold-ring",
    featured: true,
  },
  {
    id: "welcome-brother",
    name: "Welcome, Brother",
    category: "celebration",
    text: "WELCOME,\nBROTHER",
    pose: "wave",
    expression: "friendly",
    props: ["spark"],
    background: "columns",
  },
  {
    id: "proud-brother",
    name: "Proud Brother",
    category: "celebration",
    text: "PROUD\nBROTHER",
    pose: "power",
    expression: "confident",
    apron: "mm",
    background: "gold-ring",
    featured: true,
  },
  {
    id: "well-done",
    name: "Well Done",
    category: "celebration",
    text: "WELL\nDONE",
    pose: "wave",
    expression: "smile",
    props: ["spark"],
    background: "parchment",
  },
  {
    id: "wave-hello",
    name: "Wave",
    category: "expressions",
    pose: "wave",
    expression: "friendly",
    background: "none",
  },
  {
    id: "thumbs-proud",
    name: "Proud",
    category: "expressions",
    pose: "power",
    expression: "confident",
    apron: "mm",
    background: "none",
  },
  {
    id: "laughing",
    name: "Laughing",
    category: "expressions",
    pose: "idle",
    expression: "laugh",
    mouth: "grin",
    background: "none",
  },
  {
    id: "thinking",
    name: "Thinking",
    category: "expressions",
    pose: "lean",
    expression: "confident",
    background: "none",
  },
  {
    id: "coffee-and-lodge",
    name: "Coffee & Lodge",
    category: "daily",
    text: "COFFEE &\nLODGE",
    pose: "idle",
    expression: "smile",
    props: ["coffee"],
    background: "coffee",
    featured: true,
  },
  {
    id: "heading-to-lodge",
    name: "Heading to Lodge",
    category: "daily",
    text: "HEADING\nTO LODGE",
    pose: "lean",
    expression: "friendly",
    props: ["columns-pair"],
    background: "columns",
  },
  {
    id: "friday-celebration",
    name: "Happy Friday",
    category: "daily",
    text: "HAPPY\nFRIDAY",
    pose: "power",
    expression: "laugh",
    mouth: "grin",
    props: ["spark"],
    background: "parchment",
  },
  {
    id: "monday-morning",
    name: "Happy Monday",
    category: "daily",
    text: "HAPPY\nMONDAY",
    pose: "wave",
    expression: "friendly",
    props: ["sun", "coffee"],
    background: "coffee",
  },
];

export function getStickerById(id: string) {
  return STICKER_CATALOG.find((s) => s.id === id);
}

export function filterStickers(
  category: StickerCategoryMeta["id"],
  favoriteIds: Set<string>,
) {
  if (category === "all") return STICKER_CATALOG;
  if (category === "favorites") {
    return STICKER_CATALOG.filter((s) => favoriteIds.has(s.id));
  }
  return STICKER_CATALOG.filter((s) => s.category === category);
}

/** Merge sticker pose/expression/props onto the user's avatar config. */
export function applyStickerToConfig(
  base: AvatarConfig,
  sticker: StickerDefinition,
): AvatarConfig {
  return {
    ...base,
    pose: sticker.pose ?? base.pose,
    expression: sticker.expression ?? base.expression,
    mouth: sticker.mouth ?? base.mouth,
    apron: sticker.apron ?? base.apron,
    tool: sticker.tool ?? base.tool,
  };
}
