import type { StickerDefinition, StickerPack } from "@/types/stickers";

/**
 * Premium 20-card collectible sticker series.
 * Badge text is exact production copy — do not paraphrase.
 */
export const COLLECTIBLE_SERIES_STICKERS: StickerDefinition[] = [
  {
    id: "good-morning-brother",
    name: "Good Morning, Brother",
    category: "greetings",
    pack: "collectible-series",
    featured: true,
    order: 1,
    composition: {
      pose: "waving",
      expression: "happy",
      props: ["sun"],
      text: "GOOD MORNING, BROTHER",
      background: "sunRays",
      textStyle: "collectible",
    },
  },
  {
    id: "lodge-tonight",
    name: "Lodge Tonight?",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 2,
    composition: {
      pose: "pointing",
      expression: "excited",
      props: ["lodgeBuilding"],
      text: "LODGE TONIGHT?",
      background: "lodgeSilhouette",
      textStyle: "collectible",
    },
  },
  {
    id: "on-the-level",
    name: "On the Level",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 3,
    composition: {
      pose: "holdingWorkingTool",
      expression: "confident",
      props: ["level"],
      text: "ON THE LEVEL",
      background: "goldLevelLine",
      textStyle: "collectible",
      avatarOverrides: { tool: "level" },
    },
  },
  {
    id: "2b1ask1",
    name: "2B1ASK1",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 4,
    composition: {
      pose: "proud",
      expression: "confident",
      text: "2B1ASK1",
      background: "neonRing",
      textStyle: "collectible",
    },
  },
  {
    id: "traveling-man",
    name: "Traveling Man",
    category: "masonic-life",
    pack: "collectible-series",
    order: 5,
    composition: {
      pose: "walking",
      expression: "happy",
      props: ["backpack"],
      text: "TRAVELING MAN",
      background: "compassRose",
      textStyle: "collectible",
    },
  },
  {
    id: "square-and-compass",
    name: "Square & Compass",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 6,
    composition: {
      pose: "holdingWorkingTool",
      expression: "confident",
      props: ["tinySquare", "tinyCompass"],
      text: "SQUARE & COMPASS",
      background: "squareCompassMotif",
      textStyle: "collectible",
      avatarOverrides: { tool: "square-compass" },
    },
  },
  {
    id: "brotherly-love",
    name: "Brotherly Love",
    category: "celebration",
    pack: "collectible-series",
    order: 7,
    composition: {
      pose: "thumbsUp",
      expression: "happy",
      text: "BROTHERLY LOVE",
      background: "interlockingForms",
      textStyle: "collectible",
    },
  },
  {
    id: "be-true",
    name: "Be True",
    category: "masonic-life",
    pack: "collectible-series",
    order: 8,
    composition: {
      pose: "armsCrossed",
      expression: "confident",
      props: ["plumb"],
      text: "BE TRUE",
      background: "plumbLine",
      textStyle: "collectible",
      avatarOverrides: { tool: "plumb" },
    },
  },
  {
    id: "trust-the-work",
    name: "Trust the Work",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 9,
    composition: {
      pose: "standing",
      expression: "confident",
      props: ["blueprint"],
      text: "TRUST THE WORK",
      background: "blueprintGrid",
      textStyle: "collectible",
    },
  },
  {
    id: "trestleboard",
    name: "Trestleboard",
    category: "masonic-life",
    pack: "collectible-series",
    order: 10,
    composition: {
      pose: "reading",
      expression: "thinking",
      props: ["tracingBoard", "magnifier"],
      text: "TRESTLEBOARD",
      background: "draftingBoard",
      textStyle: "collectible",
    },
  },
  {
    id: "at-refreshment",
    name: "At Refreshment",
    category: "humor",
    pack: "collectible-series",
    featured: true,
    order: 11,
    composition: {
      pose: "coffee",
      expression: "happy",
      props: ["coffeeCup"],
      text: "AT REFRESHMENT",
      background: "tableSetting",
      textStyle: "collectible",
    },
  },
  {
    id: "entered-apprentice",
    name: "Entered Apprentice",
    category: "degrees",
    pack: "collectible-series",
    order: 12,
    composition: {
      pose: "standing",
      expression: "peaceful",
      text: "ENTERED APPRENTICE",
      background: "ascendingSteps",
      textStyle: "collectible",
      avatarOverrides: { apron: "ea" },
    },
  },
  {
    id: "fellowcraft",
    name: "Fellowcraft",
    category: "degrees",
    pack: "collectible-series",
    order: 13,
    composition: {
      pose: "walking",
      expression: "confident",
      text: "FELLOWCRAFT",
      background: "arches",
      textStyle: "collectible",
      avatarOverrides: { apron: "fc" },
    },
  },
  {
    id: "master-mason",
    name: "Master Mason",
    category: "degrees",
    pack: "collectible-series",
    featured: true,
    order: 14,
    composition: {
      pose: "proud",
      expression: "confident",
      props: ["squareAndCompasses"],
      text: "MASTER MASON",
      background: "starburstEmblem",
      textStyle: "collectible",
      avatarOverrides: { apron: "mm" },
    },
  },
  {
    id: "whats-your-lodge",
    name: "What's Your Lodge?",
    category: "masonic-life",
    pack: "collectible-series",
    order: 15,
    composition: {
      pose: "pointing",
      expression: "happy",
      text: "WHAT'S YOUR LODGE?",
      background: "mapPins",
      textStyle: "collectible",
    },
  },
  {
    id: "tiled",
    name: "Tiled",
    category: "masonic-life",
    pack: "collectible-series",
    order: 16,
    composition: {
      pose: "standing",
      expression: "peaceful",
      text: "TILED",
      background: "checkerboard",
      textStyle: "collectible",
    },
  },
  {
    id: "meet-on-the-level",
    name: "Meet on the Level",
    category: "celebration",
    pack: "collectible-series",
    featured: true,
    order: 17,
    composition: {
      pose: "handshake",
      expression: "happy",
      props: ["handshakePartner"],
      text: "MEET ON THE LEVEL",
      background: "parallelLines",
      textStyle: "collectible",
    },
  },
  {
    id: "seek-the-light",
    name: "Light",
    category: "masonic-life",
    pack: "collectible-series",
    featured: true,
    order: 18,
    composition: {
      pose: "standing",
      expression: "peaceful",
      props: ["lantern"],
      text: "SEEK THE LIGHT",
      background: "radiantBeam",
      textStyle: "collectible",
    },
  },
  {
    id: "brother-you-good",
    name: "Brother, You Good?",
    category: "humor",
    pack: "collectible-series",
    order: 19,
    composition: {
      pose: "leaningIn",
      expression: "concerned",
      props: ["squareAndCompasses"],
      text: "BROTHER, YOU GOOD?",
      background: "speechBubble",
      textStyle: "collectible",
    },
  },
  {
    id: "see-you-at-lodge",
    name: "See You at Lodge",
    category: "greetings",
    pack: "collectible-series",
    featured: true,
    order: 20,
    composition: {
      pose: "lookingBackWave",
      expression: "happy",
      props: ["lodgeBuilding", "moon"],
      text: "SEE YOU AT LODGE",
      background: "moonlitLodge",
      textStyle: "collectible",
    },
  },
];

export const COLLECTIBLE_SERIES_PACK: StickerPack = {
  id: "collectible-series",
  name: "Collectible Series",
  description:
    "Twenty premium lodge-inspired character stickers featuring your craftsman.",
  stickers: COLLECTIBLE_SERIES_STICKERS,
};
