import type { StickerDefinition, StickerPack } from "@/types/stickers";

/** Pack 01 — Lodge Life (first curated set). */
export const LODGE_LIFE_STICKERS: StickerDefinition[] = [
  {
    id: "good-morning-brother",
    name: "Good Morning, Brother",
    category: "greetings",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "waving",
      expression: "happy",
      props: ["coffeeCup", "sun"],
      text: "GOOD MORNING,\nBROTHER",
      background: "sunrise",
      textStyle: "banner",
    },
  },
  {
    id: "good-evening-brother",
    name: "Good Evening, Brother",
    category: "greetings",
    pack: "lodge-life",
    composition: {
      pose: "waving",
      expression: "happy",
      props: ["moon"],
      text: "GOOD EVENING,\nBROTHER",
      background: "evening",
      textStyle: "banner",
    },
  },
  {
    id: "have-a-blessed-day",
    name: "Have a Blessed Day",
    category: "greetings",
    pack: "lodge-life",
    composition: {
      pose: "prayingOrReflective",
      expression: "peaceful",
      props: ["spark"],
      text: "HAVE A\nBLESSED DAY",
      background: "parchment",
      textStyle: "banner",
    },
  },
  {
    id: "good-night-brother",
    name: "Good Night, Brother",
    category: "greetings",
    pack: "lodge-life",
    composition: {
      pose: "standing",
      expression: "sleepy",
      props: ["moon"],
      text: "GOOD NIGHT,\nBROTHER",
      background: "evening",
      textStyle: "banner",
    },
  },
  {
    id: "lodge-tonight",
    name: "Lodge Tonight?",
    category: "masonic-life",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "pointing",
      expression: "excited",
      props: ["lodgeBuilding"],
      text: "LODGE\nTONIGHT?",
      background: "lodge",
      textStyle: "banner",
    },
  },
  {
    id: "on-the-square",
    name: "On the Square",
    category: "masonic-life",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "proud",
      expression: "proud",
      props: ["squareAndCompasses"],
      text: "ON THE\nSQUARE",
      background: "goldRing",
      textStyle: "banner",
      avatarOverrides: { apron: "mm" },
    },
  },
  {
    id: "well-met",
    name: "Well Met",
    category: "masonic-life",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "greeting",
      expression: "happy",
      text: "WELL\nMET",
      background: "parchment",
      textStyle: "banner",
    },
  },
  {
    id: "traveling-brother",
    name: "Traveling Brother",
    category: "masonic-life",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "walking",
      expression: "happy",
      props: ["travelBag", "columns"],
      text: "TRAVELING\nBROTHER",
      background: "journey",
      textStyle: "banner",
    },
  },
  {
    id: "entered-apprentice",
    name: "Entered Apprentice",
    category: "degrees",
    pack: "lodge-life",
    composition: {
      pose: "proud",
      expression: "proud",
      text: "ENTERED\nAPPRENTICE",
      background: "parchment",
      textStyle: "banner",
      avatarOverrides: { apron: "ea" },
    },
  },
  {
    id: "fellow-craft",
    name: "Fellow Craft",
    category: "degrees",
    pack: "lodge-life",
    composition: {
      pose: "proud",
      expression: "proud",
      text: "FELLOW\nCRAFT",
      background: "parchment",
      textStyle: "banner",
      avatarOverrides: { apron: "fc" },
    },
  },
  {
    id: "master-mason",
    name: "Master Mason",
    category: "degrees",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "proud",
      expression: "proud",
      props: ["masonicApron"],
      text: "MASTER\nMASON",
      background: "goldRing",
      textStyle: "banner",
      avatarOverrides: { apron: "mm", tool: "gavel" },
    },
  },
  {
    id: "raising-day",
    name: "Raising Day",
    category: "degrees",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "celebrating",
      expression: "excited",
      props: ["spark", "degreeCertificate"],
      text: "RAISING\nDAY",
      background: "goldRing",
      textStyle: "banner",
      avatarOverrides: { apron: "mm" },
    },
  },
  {
    id: "coffee-promised",
    name: "I Was Told There Would Be Coffee",
    category: "humor",
    pack: "lodge-life",
    composition: {
      pose: "coffee",
      expression: "excited",
      props: ["coffeeCup"],
      text: "I WAS TOLD THERE\nWOULD BE COFFEE",
      background: "sunrise",
      textStyle: "banner",
    },
  },
  {
    id: "lodge-night-huh",
    name: "Lodge Night?",
    category: "humor",
    pack: "lodge-life",
    composition: {
      pose: "surprised",
      expression: "surprised",
      props: ["moon"],
      text: "LODGE\nNIGHT?",
      background: "evening",
      textStyle: "banner",
    },
  },
  {
    id: "one-more-question",
    name: "Just One More Question...",
    category: "humor",
    pack: "lodge-life",
    composition: {
      pose: "thinking",
      expression: "thinking",
      text: "JUST ONE MORE\nQUESTION...",
      background: "parchment",
      textStyle: "banner",
    },
  },
  {
    id: "check-the-minutes",
    name: "Let Me Check the Minutes",
    category: "humor",
    pack: "lodge-life",
    composition: {
      pose: "reading",
      expression: "serious",
      props: ["book"],
      text: "LET ME CHECK\nTHE MINUTES",
      background: "parchment",
      textStyle: "banner",
    },
  },
  {
    id: "congrats-brother",
    name: "Congratulations, Brother",
    category: "celebration",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "celebrating",
      expression: "happy",
      props: ["spark"],
      text: "CONGRATULATIONS,\nBROTHER",
      background: "goldRing",
      textStyle: "banner",
    },
  },
  {
    id: "welcome-brother",
    name: "Welcome, Brother",
    category: "celebration",
    pack: "lodge-life",
    composition: {
      pose: "greeting",
      expression: "happy",
      props: ["columns"],
      text: "WELCOME,\nBROTHER",
      background: "lodge",
      textStyle: "banner",
    },
  },
  {
    id: "well-done",
    name: "Well Done",
    category: "celebration",
    pack: "lodge-life",
    composition: {
      pose: "thumbsUp",
      expression: "proud",
      text: "WELL\nDONE",
      background: "parchment",
      textStyle: "banner",
    },
  },
  {
    id: "journey-continues",
    name: "The Journey Continues",
    category: "celebration",
    pack: "lodge-life",
    featured: true,
    composition: {
      pose: "walking",
      expression: "proud",
      props: ["travelBag"],
      text: "THE JOURNEY\nCONTINUES",
      background: "journey",
      textStyle: "banner",
    },
  },
];

export const LODGE_LIFE_PACK: StickerPack = {
  id: "lodge-life",
  name: "Lodge Life",
  description: "Greetings, lodge nights, degrees, humor, and celebration.",
  stickers: LODGE_LIFE_STICKERS,
};
